apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{.Values.httpRoute.name}}
spec:
  parentRefs:
  - name: {{.Values.httpRoute.parentRef.name}}
    namespace: {{.Values.httpRoute.parentRef.namespace}}
    sectionName: {{.Values.httpRoute.parentRef.sectionName}}
  hostnames:
  - {{.Values.httpRoute.host | quote}}
  rules:
  - matches:
    - path:
        type: {{.Values.httpRoute.pathType}}
        value: {{.Values.httpRoute.path}}
    backendRefs:
    - name: {{.Values.nameOverride}}
      port: {{.Values.httpRoute.backend.service.port.number}}
