kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: handson-analysis
spec:
  metrics:
  - name: handson-analysis
    successCondition: result == "hym"
    failureLimit: 3
    provider:
      web:
        url: "http://handson-preview.web-analysis.svc.cluster.local/color"
        insecure: true
