repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: grafana-tempo
  namespace: monitoring
  createNamespace: true
  chart: grafana/tempo
  version: 1.23.3
  values: 
    - tempo-values.yaml
