# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver
# https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/debugexporter
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/fileexporter
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: log-collector
spec:
  mode: "daemonset"
  volumeMounts:
    - name:  host-log-volumes
      mountPath: /var/log
  volumes:
    - name: host-log-volumes
      hostPath:
        path:  /var/log
  config:
    receivers:
      filelog:
        include: [ /var/log/pods/handson_handson-*/*/*.log]
        operators:
        # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/types/timestamp.md#example-configurations
        - type: regex_parser
          regex: (?P<timestamp_field>^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+Z)
          timestamp:
            layout: "%Y-%m-%d %H:%M:%S.%f"
            parse_from: attributes.timestamp_field
        - type: time_parser
          parse_from: attributes.timestamp_field
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        - type: remove
          field: attributes.timestamp_field

    processors:
      # resource processorでexporterラベルをOTLPに設定
      # これにより、README.mdで指定されているexporter="OTLP"での検索にヒットする
      resource:
        attributes:
          - key: exporter
            value: OTLP
            action: upsert

    exporters:
      # OTLP HTTP exporterを使用してLokiにログを送信
      # Loki 3.0以降はOTLPプロトコルをサポートしている
      # エンドポイントはLokiのOTLPエンドポイントを指定
      otlphttp:
        endpoint: http://loki-gateway.monitoring.svc.cluster.local/otlp
        headers:
          X-Scope-OrgID: tenant1
        tls:
          # ハンズオン環境のため、自己署名証明書のエラーを回避するために証明書の検証を無効化します。
          # 本番環境では、適切な証明書を設定し、このオプションをtrueにしないでください。
          insecure: true

    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors: [resource]
          exporters: [otlphttp]
