apiVersion: batch/v1
kind: CronJob
metadata:
  name: handson-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: handson-cronjob
            image: centos:latest
            command:
            - sh
            - -c
            args:
            - date
          restartPolicy: Never
