apiVersion: batch/v1
kind: Job
metadata:
  name: handson-job
spec:
  completions: 6
  parallelism: 2
  template:
    spec:
      containers:
      - name: handson-job
        image: alpine:latest
        command: ["echo"]
        args: ["Welcome To the CNDW2025 Hands On Event!!"]
      restartPolicy: Never
