apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: handson
  name: handson
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: handson
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: handson
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: ghcr.io/cloudnativedaysjp/cnd-handson-app/handson:legacy
        imagePullPolicy: Always
        name: handson
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        # handson namespace に入れたバックエンドにつなぐ
        env:
        - name: IDP_ADDR
          value: handson-idp.handson:50051
        - name: IDP_JWKS_URL
          value: http://handson-idp.handson:8080/.well-known/jwks.json
        - name: IDP_ISS
          value: http://handson-idp:8080
        - name: IDP_AUD
          value: handson
        - name: PROJECT_ADDR
          value: handson-project.handson:50051
        - name: TASK_ADDR
          value: handson-task.handson:50051
        - name: COLUMN_ADDR
          value: handson-column.handson:50051
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
      terminationGracePeriodSeconds: 15
