apiVersion: v1
kind: Namespace
metadata:
  name: oom-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hungry-app
  namespace: oom-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hungry
  template:
    metadata:
      labels:
        app: memory-hungry
    spec:
      containers:
      - name: app
        image: polinux/stress:1.0.4
        command: ["stress"]
        args:
        - "--vm"
        - "1"
        - "--vm-bytes"
        - "256M"
        - "--vm-hang"
        - "0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: memory-hungry-service
  namespace: oom-demo
spec:
  selector:
    app: memory-hungry
  ports:
  - port: 80
    targetPort: 8080
