apiVersion: v1
kind: Namespace
metadata:
  name: scheduling-demo
---
# このマニフェストを適用する前に、以下のコマンドでNodeにtaintを設定してください:
# kubectl taint nodes <node-name> workload=batch:NoSchedule
#
# 確認方法:
# kubectl describe node <node-name> | grep Taint
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-app
  namespace: scheduling-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch-app
  template:
    metadata:
      labels:
        app: batch-app
    spec:
      containers:
      - name: app
        image: busybox:1.36
        command: ["sh", "-c", "echo Starting batch job && sleep 3600"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      tolerations:
      # 問題: tolerationの設定が間違っている！
      # effectがNoExecuteになっているが、NodeのtaintはNoSchedule
      - key: "workload"
        operator: "Equal"
        value: "batch"
        effect: "NoExecute"
