---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
# Envoy Gatewayが起動するEnvoyのService/Deploymentの設定。
# kindにはクラウドプロバイダーのロードバランサーが無いため、
# Serviceを`Type: NodePort`にしてkind-config.yamlのextraPortMappings経由で公開する。
#   see: https://gateway.envoyproxy.io/docs/tasks/operations/customize-envoyproxy/
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: handson-proxy
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
      envoyService:
        type: NodePort
        patch:
          type: StrategicMerge
          value:
            spec:
              ports:
              # StrategicMergeではportsの要素は`port`をキーにマージされるため、
              # Gatewayのlistenerのポート番号を指定する
              - port: 80
                nodePort: 30080
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: handson-proxy
    namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: handson-gateway
  namespace: gateway
spec:
  gatewayClassName: eg
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        # ハンズオンの全chapterからHTTPRouteを紐付けられるようにする
        from: All
