repositories:
- name: cilium
  url: https://helm.cilium.io

releases:
- name: cilium
  namespace: kube-system
  chart: cilium/cilium
  version: 1.20.2
  values:
  - values/cilium.values.yaml
- name: envoy-gateway
  namespace: envoy-gateway-system
  createNamespace: true
  chart: oci://docker.io/envoyproxy/gateway-helm
  version: v1.9.1
  values:
  - values/envoy-gateway.values.yaml
  # CNIが動いていないとEnvoy GatewayのPodが起動できないため、Ciliumの後にデプロイする
  needs:
  - kube-system/cilium
