apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-vm
  labels:
    app: fedora
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/vm: fedora-vm
    spec:
      domain:
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
          rng: {}
        resources:
          requests:
            memory: 2Gi
            cpu: "1"
          limits:
            memory: 2Gi
            cpu: "1"
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: containerdisk
        containerDisk:
          image: kubevirt/fedora-cloud-container-disk-demo:latest
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
              #cloud-config
              password: password
              chpasswd: { expire: False }