ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts: 
    - host: headlamp.example.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: handson
              port:
                name: http
