name: Watch Deployment Changes

on:
  push:
    branches:
      - cndw2024  # 監視対象のブランチ
    paths:
      - 'chapter_argocd/app/default/deployment.yaml'  # 監視対象のファイル

jobs:
  detect-deployment-change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Notify Change
        run: echo "chapter_argocd/app/default/deployment.yaml has been modified!"
