name: Detect Deployment Image Change

on:
  push:
    branches:
      - main
    paths:
      - chapter_argocd/app/default/deployment.yaml

jobs:
  detect-and-validate-change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # フル履歴を取得して差分を確実に解析

      - name: Check Deployment Image Changes
        id: check_image_changes
        run: |
          # 差分を取得
          if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
              DIFF_CMD="git diff HEAD^ HEAD -- chapter_argocd/app/default/deployment.yaml"
          else
              DIFF_CMD="git show HEAD -- chapter_argocd/app/default/deployment.yaml"
          fi
          DIFF_OUTPUT=$($DIFF_CMD || true)

          # デバッグ用に差分全体を出力
          echo "Debug: Full DIFF_OUTPUT:"
          echo "$DIFF_OUTPUT"

          # 差分行をフィルタリング（デバッグ用）
          echo "Debug: Filtered Diff Lines:"
          FILTERED_LINES=$(echo "$DIFF_OUTPUT" | grep '^\+\s*- image:argoproj/rollouts-demo:')
          echo "$FILTERED_LINES"

          # イメージタグの抽出
          CHANGED_IMAGE=$(echo "$FILTERED_LINES" | sed -E 's/^\+\s*- image:argoproj\/rollouts-demo:(.*)$/\1/' | tr -d '\r')
          echo "Debug: Extracted Image Tag is '$CHANGED_IMAGE'"

          # タグが抽出できない場合のスキップ処理
          if [ -z "$CHANGED_IMAGE" ]; then
              echo "No image tag found in the changes. Skipping workflow."
              exit 0
          fi

          # 青か緑かの条件判定
          if [ "$CHANGED_IMAGE" == "blue" ]; then
              echo "Detected a valid image tag: blue"
              echo "change_type=blue" >> $GITHUB_ENV
          elif [ "$CHANGED_IMAGE" == "green" ]; then
              echo "Detected a valid image tag: green"
              echo "change_type=green" >> $GITHUB_ENV
          else
              echo "===================================="
              echo "⚠️ WARNING: Invalid Image Tag Detected."
              echo "Unsupported Image Tag: $CHANGED_IMAGE"
              echo "File: chapter_argocd/app/default/deployment.yaml"
              echo "===================================="
              echo "Detected Invalid Image Version: $CHANGED_IMAGE" | tee -a INVALID_IMAGE_ALERT.log
              echo "change_type=invalid" >> $GITHUB_ENV
              exit 1
          fi
