name: Detect Deployment Image Change

on:
  push:
    branches:
      - main
    paths:
      - chapter_argocd/app/default/deployment.yaml

jobs:
  detect-and-validate-change:
    runs-on: ubuntu-latest

    steps:
      # 1. ソースコードをチェックアウト
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. 修正箇所を確認
      - name: Check for Image Changes
        id: check_image_changes
        run: |
          # `deployment.yaml` の変更を取得
          CHANGED_IMAGE=$(git diff HEAD^ HEAD -- chapter_argocd/app/default/deployment.yaml | grep '\- image:' | awk '{print $3}' | cut -d':' -f2 | tr -d '\r')

          echo "Detected Changed Images: $CHANGED_IMAGE"

          # blue と green のタグを確認
          if echo "$CHANGED_IMAGE" | grep -q "blue"; then
            echo "Detected Blue tag"
            echo "change_type=blue" >> $GITHUB_ENV
          elif echo "$CHANGED_IMAGE" | grep -q "green"; then
            echo "Detected Green tag"
            echo "change_type=green" >> $GITHUB_ENV
          else
            # blue でも green でもないタグが検出された場合の警告
            echo "Warning: The image tag is neither blue nor green: $CHANGED_IMAGE"
            echo "Detected Invalid Image Version: $CHANGED_IMAGE" | tee -a INVALID_IMAGE_ALERT.log
            echo "change_type=invalid" >> $GITHUB_ENV
            exit 1
          fi

      # 3. アラートメッセージを表示（無効なタグが存在する場合）
      - name: Show Alert for Invalid Tags
        if: env.change_type == 'invalid'
        run: |
          echo "ALERT: Invalid image tag detected in 'deployment.yaml'!"
          echo "Please check the file. Invalid tag: $CHANGED_IMAGE"

      # 4. 正常な変更に応じて出力
      - name: Handle Valid Changes
        if: env.change_type != 'invalid'
        run: |
          echo "Valid image change detected (To: ${{ env.change_type }}). Proceeding..."
