name: Detect Deployment Image Change

on:
  push:
    branches-ignore:
      - '' # 空の値で「すべてのブランチ」を対象に設定
    paths:
      - chapter_argocd/app/default/deployment.yaml

jobs:
  detect-and-validate-change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 全履歴をクローン

      - name: Detect Deployment Image Changes
        run: |
          # 差分取得コマンドの分岐（通常コミットか初回コミットかを判定）
          if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
              DIFF_CMD="git diff HEAD^ HEAD -- chapter_argocd/app/default/deployment.yaml"
          else
              DIFF_CMD="git show HEAD -- chapter_argocd/app/default/deployment.yaml"
          fi
          DIFF_OUTPUT=$($DIFF_CMD || true)

          # ログ: 差分全体を出力
          echo "Debug: Full DIFF_OUTPUT:"
          echo "$DIFF_OUTPUT"

          # 差分行をフィルタリング（フィルタ条件: `+` が含まれる `image:argoproj/rollouts-demo` の行）
          FILTERED_LINES=$(echo "$DIFF_OUTPUT" | grep '^\+[[:space:]]*- image:.*argoproj/rollouts-demo:')
          echo "Debug: Filtered Diff Lines:"
          echo "$FILTERED_LINES"

          # イメージタグを抽出
          CHANGED_IMAGE=$(echo "$FILTERED_LINES" | sed -E 's/^\+[[:space:]]*- image:.*argoproj\/rollouts-demo:(.*)$/\1/' | tr -d '\r')
          echo "Debug: Extracted Image Tag is '$CHANGED_IMAGE'"

          # タグが抽出されない場合のスキップ処理
          if [ -z "$CHANGED_IMAGE" ]; then
              echo "No image tag found in the changes. Skipping workflow."
              exit 0
          fi

          # 無効なタグ検出
          if [ "$CHANGED_IMAGE" != "blue" ] && [ "$CHANGED_IMAGE" != "green" ]; then
              echo "===================================="
              echo "⚠️ WARNING: Invalid Image Tag Detected."
              echo "Unsupported Image Tag: $CHANGED_IMAGE"
              echo "File: chapter_argocd/app/default/deployment.yaml"
              echo "===================================="
              echo "Detected Invalid Image Version: $CHANGED_IMAGE" | tee -a INVALID_IMAGE_ALERT.log
              exit 1
          fi

          # タグが有効な場合は正常終了処理
          if [ "$CHANGED_IMAGE" == "blue" ]; then
              echo "Detected valid image tag: blue"
          fi
          if [ "$CHANGED_IMAGE" == "green" ]; then
              echo "Detected valid image tag: green"
          fi
