name: Detect Deployment Image Change

on:
  push:
    branches:
      - cndw2024
    paths:
      - chapter_argocd/app/default/deployment.yaml

jobs:
  detect-and-validate-change:
    runs-on: ubuntu-latest

    steps:
      # 1. ソースコードをチェックアウト
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. 修正箇所を確認
      - name: Check for Image Changes
        id: check_image_changes
        run: |
          # Check for blue → green or green → blue changes in `deployment.yaml`
          if git diff HEAD^ HEAD -- chapter_argocd/app/default/deployment.yaml | grep -q '\- image: argoproj/rollouts-demo:blue'; then
            if git diff HEAD^ HEAD -- chapter_argocd/app/default/deployment.yaml | grep -q '\- image: argoproj/rollouts-demo:green'; then
              echo "Blue-to-Green change detected."
              echo "image_changed=true" >> $GITHUB_ENV
              echo "change_type=blue_to_green" >> $GITHUB_ENV
            fi
          elif git diff HEAD^ HEAD -- chapter_argocd/app/default/deployment.yaml | grep -q '\- image: argoproj/rollouts-demo:green'; then
            if git diff HEAD^ HEAD -- chapter_argocd/app/default/deployment.yaml | grep -q '\- image: argoproj/rollouts-demo:blue'; then
              echo "Green-to-Blue change detected."
              echo "image_changed=true" >> $GITHUB_ENV
              echo "change_type=green_to_blue" >> $GITHUB_ENV
            fi
          else
            echo "No relevant image changes detected."
            echo "image_changed=false" >> $GITHUB_ENV
          fi

      # 3. CI を実行するかの判定
      - name: Run CI if Image Changed
        if: env.image_changed == 'true'
        run: |
          echo "Running CI because the image change was detected."
          echo "Change type: ${{ env.change_type }}"
          # 実行したいCIプロセスをここに記述
