name: Detect Deployment Image Change

on:
  push:
    branches:
      - cndw2024
    paths:
      - chapter_argocd/app/default/deployment.yaml

jobs:
  detect-and-validate-change:
    runs-on: ubuntu-latest

    steps:
      # 1. ソースコードをチェックアウト
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. 修正箇所を確認
      - name: Check for Image Changes
        id: check_image_changes
        run: |
          # Extract image tag changes from the diff
          CHANGED_IMAGE=$(git diff HEAD^ HEAD -- chapter_argocd/app/default/deployment.yaml | grep '\- image:' | awk '{print $3}' | cut -d':' -f2 | tr -d '\r')

          echo "Detected Changed Images: $CHANGED_IMAGE"

          HAS_BLUE=$(echo "$CHANGED_IMAGE" | grep -c "blue")
          HAS_GREEN=$(echo "$CHANGED_IMAGE" | grep -c "green")
          INVALID=${CHANGED_IMAGE}

          # Detect blue->green and green->blue transitions
          if [ "$HAS_BLUE" -gt 0 ] && [ "$HAS_GREEN" -gt 0 ]; then
            if git diff HEAD^ HEAD -- chapter_argocd/app/default/deployment.yaml | grep -q '\- image: argoproj/rollouts-demo:blue' && git diff HEAD^ HEAD -- chapter_argocd/app/default/deployment.yaml | grep -q '\- image: argoproj/rollouts-demo:green'; then
              echo "Blue-to-Green change detected."
              echo "image_changed=true" >> $GITHUB_ENV
              echo "change_type=blue_to_green" >> $GITHUB_ENV
            fi
            if git diff HEAD^ HEAD -- chapter_argocd/app/default/deployment.yaml | grep -q '\- image: argoproj/rollouts-demo:green' && git diff HEAD^ HEAD -- chapter_argocd/app/default/deployment.yaml | grep -q '\- image: argoproj/rollouts-demo:blue'; then
              echo "Green-to-Blue change detected."
              echo "image_changed=true" >> $GITHUB_ENV
              echo "change_type=green_to_blue" >> $GITHUB_ENV
            fi
          elif [ "$HAS_BLUE" -eq 0 ] && [ "$HAS_GREEN" -eq 0 ]; then
            echo "Warning: The image tag is neither blue nor green."
            echo "image_changed=false" >> $GITHUB_ENV
            echo "change_type=invalid" >> $GITHUB_ENV
            echo "\\nDetected Invalid Image Version: $INVALID\\nAction Required: Please check the image tag in 'deployment.yaml'." | tee -a INVALID_IMAGE_ALERT.log
          else
            echo "No relevant image changes detected."
            exit manually prompted;
